#!/bin/bash

mv TxtFiles_Thickness_vs_AttenuationNeutron/Thickness_vs_AttenuationNeutron.txt TxtFiles_Thickness_vs_AttenuationNeutron/Gamma/Thickness_vs_AttenuationNeutron_WaterOnly_${i}MeV.txt
mv TxtFiles_Thickness_vs_AttenuationGamma/Thickness_vs_AttenuationGamma.txt TxtFiles_Thickness_vs_AttenuationGamma/Gamma/Thickness_vs_AttenuationGamma_WaterOnly_${i}MeV.txt
mv TxtFiles_Thickness_vs_AttenuationAllPart/Thickness_vs_AttenuationAllPart.txt TxtFiles_Thickness_vs_AttenuationAllPart/Gamma/Thickness_vs_AttenuationAllPart_WaterOnly_${i}MeV.txt
mv TxtFiles_Thickness_vs_AttenuationGenerator/Thickness_vs_AttenuationGenerator.txt TxtFiles_Thickness_vs_AttenuationGenerator/Gamma/Thickness_vs_AttenuationGenerator_WaterOnly_${i}MeV.txt
