#!/bin/bash

mv TxtFiles_Thickness_vs_AttenuationNeutron/Thickness_vs_AttenuationNeutron.txt TxtFiles_Thickness_vs_AttenuationNeutron/Neutron/Concrete/Thickness_vs_AttenuationNeutron_BWater_${1}MeV.txt
mv TxtFiles_Thickness_vs_AttenuationGamma/Thickness_vs_AttenuationGamma.txt TxtFiles_Thickness_vs_AttenuationGamma/Neutron/Concrete/Thickness_vs_AttenuationGamma_BWater_${1}MeV.txt
mv TxtFiles_Thickness_vs_AttenuationAllPart/Thickness_vs_AttenuationAllPart.txt TxtFiles_Thickness_vs_AttenuationAllPart/Neutron/Concrete/Thickness_vs_AttenuationAllPart_BWater_${1}MeV.txt
mv TxtFiles_Thickness_vs_AttenuationGenerator/Thickness_vs_AttenuationGenerator.txt TxtFiles_Thickness_vs_AttenuationGenerator/Neutron/Concrete/Thickness_vs_AttenuationGenerator_BWater_${1}MeV.txt
