#!/bin/bash

mv TxtFiles_Thickness_vs_AttenuationNeutron/Thickness_vs_AttenuationNeutron.txt TxtFiles_Thickness_vs_AttenuationNeutron/Neutron/AttenuationNeutron_IronTop.txt
mv TxtFiles_Thickness_vs_AttenuationGamma/Thickness_vs_AttenuationGamma.txt TxtFiles_Thickness_vs_AttenuationGamma/Neutron/AttenuationGamma_IronTop.txt
mv TxtFiles_Thickness_vs_AttenuationAllPart/Thickness_vs_AttenuationAllPart.txt TxtFiles_Thickness_vs_AttenuationAllPart/Neutron/AttenuationAllPart_IronTop.txt
mv TxtFiles_Thickness_vs_AttenuationGenerator/Thickness_vs_AttenuationGenerator.txt TxtFiles_Thickness_vs_AttenuationGenerator/Neutron/AttenuationGenerator_IronTop.txt
